apiVersion: v2
appVersion: "v0.6.0"
version: "1.1.0"
type: application
name: cnwan-operator
description: |
  Register and manage your Kubernetes Services to a Service Registry.

  `v0.6.0` improves the way to instruct the operator to watch or ignore events
  occurring on a namespace: `allowlist` and `blocklist` have been removed in
  favor of a simpler `EnableNamespacesByDefault`, which can be either be `true`
  or `false`.

  `operator.cnwan.io/allowed` and `operator.cnwan.io/blocked` are removed in
  favor of just `operator.cnwan.io/monitor`, which can be either `true` or
  `false`.

  Some other improvements are also present.
# https://github.com/helm/helm/issues/6190
kubeVersion: ">= 1.11.0-0"
home: https://github.com/CloudNativeSDWAN/cnwan-operator
icon: https://avatars.githubusercontent.com/u/66446392?s=200&v=4
keywords:
  - cluster
  - sd-wan
  - networking
  - service-registry
maintainers:
  - name: CloudNativeSDWAN
    email: cnwan@cisco.com
    url: https://github.com/CloudNativeSDWAN/cnwan-operator/blob/master/OWNERS.md
sources:
  - https://github.com/CloudNativeSDWAN/cnwan-operator
dependencies:
- name: etcd
  version: "> 6.2.0"
  repository: https://charts.bitnami.com/bitnami
  condition: operator.etcd.install
