apiVersion: v2
appVersion: "v0.6.0"
version: "1.1.1"
type: application
name: cnwan-operator
description: |
  Register and manage your Kubernetes Services to a Service Registry.

  `v0.6.0` removes the old way of filtering namespaces to be watched with a
  more intuitive way: instead of using concepts like `allowlist` or
  `blocklist`, one can just set `true` or `false` in the new
  `watchNamespacesByDefault`.

  The old labels used to filter them are now dropped in favor of just
  `operator.cnwan.io/watch` with values `enabled` or `disabled`.
  Please refer to our documentation to know how this works.

  The old, deprecated way to provide options for Google Service Directory is
  now definitively removed and some other packages have been removed as well,
  making the project slimmer and smoother.

  Some other improvements are also present.
# https://github.com/helm/helm/issues/6190
kubeVersion: ">= 1.11.0-0"
home: https://github.com/CloudNativeSDWAN/cnwan-operator
icon: https://avatars.githubusercontent.com/u/66446392?s=200&v=4
keywords:
  - cluster
  - sd-wan
  - networking
  - service-registry
maintainers:
  - name: CloudNativeSDWAN
    email: cnwan@cisco.com
    url: https://github.com/CloudNativeSDWAN/cnwan-operator/blob/master/OWNERS.md
sources:
  - https://github.com/CloudNativeSDWAN/cnwan-operator
dependencies:
- name: etcd
  version: "> 6.2.0"
  repository: https://charts.bitnami.com/bitnami
  condition: operator.etcd.install
