{{- if eq (lower .Values.operator.serviceRegistry) "cloudmap" }}
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
data:
  credentials: |-
{{ required "credentials is empty" .Values.operator.awsCloudMap.credentials | b64enc | indent 4 }}
{{- end }}
