apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name}}-settings
data:
  settings.yaml: |-
      namespace:
        {{- if and (ne .Values.operator.namespaceListPolicy "allowlist") (ne .Values.operator.namespaceListPolicy "blocklist") }}
        {{- fail "namespaceListPolicy must be either allowlist or blocklist" }}
        {{- else }}
        listPolicy: {{ .Values.operator.namespaceListPolicy }}
        {{- end }}
      service:
        {{- if .Values.operator.serviceAnnotations }}
        annotations:
        {{- range .Values.operator.serviceAnnotations }}
          - {{ . }}
        {{- end }}
        {{- else }}
        {{- fail "no service annotations provided" }}
        {{- end }}
      serviceRegistry:
        {{- if and (ne (lower .Values.operator.serviceRegistry) "etcd") (ne (lower .Values.operator.serviceRegistry) "servicedirectory") }}
        {{- fail "service registry defined in serviceRegistry is empty or not supported" }}
        {{- end }}
        {{- if eq (lower .Values.operator.serviceRegistry) "etcd" }}
        etcd:
          prefix: {{ .Values.operator.etcd.prefix }}
          {{- if or (.Values.operator.etcd.username) (.Values.operator.etcd.password) }}
          authentication: WithUsernameAndPassword
          {{- end }}
          {{- if .Values.operator.etcd.install }}
          endpoints:
            - host: {{ .Values.etcd.fullnameOverride }}.{{ .Release.Namespace }}
          {{- else }}
          {{- if .Values.operator.etcd.endpoints }}
          endpoints:
          {{- range .Values.operator.etcd.endpoints }}
          {{- $parts := split ":" . }}
            - host: {{ $parts._0 }}
              {{- if $parts._1 }}
              port: {{ $parts._1 }}
              {{- end }}
          {{- end }}
          {{- else }}
          {{- fail "no etcd endpoints provided" }}
          {{- end }}
          {{- end }}
        {{- end }}
        {{- if eq (lower .Values.operator.serviceRegistry) "servicedirectory" }}
        {{- if or (.Values.operator.googleServiceDirectory.defaultRegion) (.Values.operator.googleServiceDirectory.projectID) }}
        gcpServiceDirectory:
          {{- if .Values.operator.googleServiceDirectory.defaultRegion }}
          defaultRegion: {{ .Values.operator.googleServiceDirectory.defaultRegion }}
          {{- end }}
          {{- if .Values.operator.googleServiceDirectory.projectID }}
          projectID: {{ .Values.operator.googleServiceDirectory.projectID }}
          {{- end }}
        {{- else }}
        gcpServiceDirectory: {}
        {{- end }}
        {{- end }}
        {{- if and
          (.Values.operator.cloudMetadata)
          (or (.Values.operator.cloudMetadata.network) (.Values.operator.cloudMetadata.subNetwork) )
        }}
        cloudMetadata:
          {{- if .Values.operator.cloudMetadata.network }}
          network: {{ .Values.operator.cloudMetadata.network }}
          {{- end }}
          {{- if .Values.operator.cloudMetadata.subNetwork }}
          subNetwork: {{ .Values.operator.cloudMetadata.subNetwork }}
          {{- end }}
        {{- end }}