{{- if and (eq .Values.operator.serviceRegistry "etcd") (or (.Values.operator.etcd.username) (.Values.operator.etcd.password)) }}
apiVersion: v1
kind: Secret
metadata:
  name: etcd-credentials
data:
  username: {{ .Values.operator.etcd.username | b64enc }}
  password: {{ .Values.operator.etcd.password | b64enc }}
{{- end }}
