{{- if and (eq (lower .Values.operator.serviceRegistry) "etcd") (.Values.operator.etcd.install) }}
apiVersion: v1
kind: Secret
metadata:
  name: etcd-root-password
data:
  etcd-root-password: {{ .Values.operator.etcd.password | b64enc }}
{{- end }}
