{{- if and (eq .Values.operator.serviceRegistry "etcd") (or (.Values.operator.etcd.username) (.Values.operator.etcd.password)) }}

{{- if (and (.Values.operator.etcd.username) (not .Values.operator.etcd.password) ) }}
{{- fail "etcd password not provided" }}
{{- end }}
{{- if (and (not .Values.operator.etcd.username) (.Values.operator.etcd.password) ) }}
{{- fail "etcd username not provided" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: etcd-credentials
data:
  username: {{ .Values.operator.etcd.username | b64enc }}
  password: {{ .Values.operator.etcd.password | b64enc }}
{{- end }}
