{{- if eq (lower .Values.operator.serviceRegistry) "servicedirectory" }}
apiVersion: v1
kind: Secret
metadata:
  name: google-service-account
data:
  google-service-account.json: |-
{{ required "serviceAccount is empty" .Values.operator.googleServiceDirectory.serviceAccount | b64enc | indent 4 }}
{{- end }}
