name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.email cnwan@cisco.com
          git config user.name CN-WAN Bot

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: latest

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  update-index:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: charts-pages

      - name: Copy index.yaml
        run: cp charts-pages/index.yaml index.yaml

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main

      - name: Move index.yaml
        run: mv index.yaml main/index.yaml

      - name: Configure Git
        run: |
          cd main
          git config user.email cnwan@cisco.com
          git config user.name CN-WAN Bot

      - name: Commit and push changes
        run: |
          cd main
          git pull
          git add .
          git commit -s -m "Generate index.yaml"
          git push
