name: Test chart

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: latest

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch=main)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Add bitnami/etcd repo
        run: helm repo add bitnami https://charts.bitnami.com/bitnami
        if: steps.list-changed.outputs.changed == 'true'

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        id: create-kind
        if: steps.list-changed.outputs.changed == 'true'

      - name: Create cnwan-operator-system namespace
        run: kubectl create ns cnwan-operator-system
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install --namespace cnwan-operator-system
        if: steps.list-changed.outputs.changed == 'true'
